nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  react-scripts@*:
    dependencies:
      crypto-browserify: '*'
      stream-browserify: '*'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
