nodeLinker: node-modules

# Some dependencies used by this project use Node built-ins, which aren't
# available on the web. `react-scripts@5` uses webpack 5, which no longer
# provides polyfills, so we need to manually inject the polyfills in ourselves.
packageExtensions:
  react-scripts@*:
    dependencies:
      assert-browserify: '*'
      buffer-browserify: '*'
      crypto-browserify: '*'
      stream-browserify: '*'
  # This just fixes a missing package from @graphiql/toolkit
  # (Module not found: Error: Can't resolve 'graphql-ws' in 'C:\Users\Reece\WebstormProjects\cirrus-ci-web\node_modules\@graphiql\toolkit\esm\create-fetcher')
  '@graphiql/toolkit@*':
    dependencies:
      graphql-ws: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
